<a href="https://colab.research.google.com/github/worldwidekatie/DS-Unit-4-Sprint-2-Neural-Networks/blob/main/module1-Intro-to-Neural-Networks/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### **Input Layer:** The input layer is the nodes that represent the data you put into it, like the features or a bias.

### **Hidden Layer:** Hidden layers are the nodes that are hidden from us but it's where the magic happens. It's like the neurons with the different functions that pass information to each other to eventually come to a decision.


### **Output Layer:** This is the node(s) of output, like predictions, prediction probability, recommendations, etc.


### **Neuron:** The neurons are the individual nodes.


### **Weight:** The weights are the neural network equivalent to coefficients and determine how it precdits stuff given different feature values.


### **Activation Function:** Activation function is the control valve for the neurons that controls how much information flows between neurons, whether a cell fires and how much it functions.


### **Node Map:** Node maps are a visual diagram of the architecture of neural networks. It's like a flow chart with input, output, and hidden layers.


### **Perceptron:** TODO

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

We begin with the input layer consisting of the input or feature nodes and perhaps a bias, which is the neural network equivalent of an intercept to start you off. It then moves through the hidden layer nodes and their weights according to the instructions from the activation function. It ends on the output layer, which is the nodes representing the output of the model.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [ ]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [ ]:
inputs = ['x1', 'x2']
output = 'y'

X_train = np.array(df[inputs])
Y_train = tuple(df[output])

In [ ]:
y_train = []
for i in Y_train:
  y_train.append([i])

y_train = tuple(y_train)
y_train

([1], [1], [1], [0])

In [ ]:
#make sigmoid functions

def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_der(x):
  sx = sigmoid(x)
  return sx*(1-sx)


In [ ]:
# Make random weights. 
import numpy as np

weights = 2*np.random.random((2,1))-1
weights

array([[-0.66174444],
       [-0.11881769]])

In [ ]:
# calculate weighted sum of inputs and weights
weighted_sum = np.dot(X_train, weights)
weighted_sum

array([[ 0.        ],
       [-0.66174444],
       [-0.11881769],
       [-0.78056212]])

In [ ]:
# output the activated value for the end of 1 training epoch
y_pred = np.array(sigmoid(weighted_sum))
y_pred


array([[0.5       ],
       [0.34034786],
       [0.47033048],
       [0.31419875]])

In [ ]:
# take difference of output and true values to calcuate error
error = y_train - y_pred
error

array([[ 0.5       ],
       [ 0.65965214],
       [ 0.52966952],
       [-0.31419875]])

In [ ]:
# do gradient descent iterative updating of weights

adjustments = error * sigmoid_der(weighted_sum)
adjustments

array([[ 0.125     ],
       [ 0.14809929],
       [ 0.13195112],
       [-0.06770288]])

In [ ]:
# adjusted weights
weights = np.dot(X_train.T, adjustments)
weights

array([[0.0803964 ],
       [0.06424824]])

In [ ]:
# update weights 10,000 times

for iteration in range(10000):

  # weighted sum of inputs/weights
  weighted_sum = np.dot(X_train, weights)

  # activate
  activated_output = sigmoid(weighted_sum)

  # cac error
  error = y_train - activated_output
  adjustments = error*sigmoid_der(weighted_sum)

  #update weights
  weights += np.dot(X_train.T, adjustments)

print("weights after training")
print(weights)
print(" ")
print("Output after training")
print(activated_output)

weights after training
[[ 1.52655666e-16]
 [-3.05311332e-16]]
 
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


That's pretty darn awful. I'm gonna make the class thing and see if that does any better.


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [ ]:
# TODO if I have time to come back and figure it out
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
# Making it smaller to test stuff out quicker
df = diabetes.head(10)

In [ ]:
diabetes.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
features = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]
target = df['Outcome']

input = np.array(features)
output = tuple(target)

In [ ]:
class Perceptron(object):
    X = None
    y = None
    niter = None
    #np.random.seed(812)
    
    def __init__(self, a, b, niter=1000, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.a = a
        self.b = b
        self.niter = niter

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
      
    def sigmoid_derivative(self, x):
        sx = self.sigmoid(x)
        return sx * (1-sx)

    def fit(self):
      a = self.a
      b = self.b
      z = len(a[0])
      weights = 2 * np.random.random((z,1)) -1

      if type(b[0]) == int:
        var = []
        for i in b:
          var.append([i])
        b = tuple(var)

      for iteration in range(self.niter):
        
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(a, weights)
        
        # Activate!
        activated_output = self.sigmoid(weighted_sum)
        
        # Cac error
        error = b - activated_output
        
        adjustments = error * self.sigmoid_derivative(weighted_sum)
        weights += np.dot(a.T, adjustments)
        
        # Update the Weights
      # weights += np.dot(a.T, adjustments)
      return activated_output

    def predict(self):
      predictions = []
      for i in self.fit():
        predictions.append(round(i[0], 2))
      return predictions


percept = Perceptron(inputs, correct_outputs)
#percept = Perceptron(input, output)
percept.fit()
percept.predict()
# Can't figure out why it works fine on inputs/correct_outputs
# But is completely useless on everything else.

[0.03, 0.97, 0.98, 0.03, 1.0]

In [ ]:
percept = Perceptron(input, output)
percept.predict()
# For example, this is absolutely useless.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [ ]:
inputs = np.array([[0,0,1],
                   [1,1,1],
                   [1,0,1],
                   [0,1,1],
                   [1,0,0]])

correct_outputs = ([0], [1], [1], [0], [1])

precep = Perceptron(inputs, correct_outputs)
precep

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?